### ISSUE TITLE
有没有封号的风险啊

### ISSUE THREAD

**Issue by MaLin1997** [lgpersonal/LazyStudy#10]
红米 K20 Pro 评论分享也会报错

**Comment by lgpersonal** [comment]
你把报错内容发下

**Comment by MaLin1997** [comment]
Thread[ScriptThread-6[/data/user/0/com.lazyStudy/files/project/floating.js] (Spawn-0),5]: TypeError: Cannot call method "click" of null (file:/data/data/com.lazyStudy/files/project/liulan.js#347)
TypeError: Cannot call method "click" of null
    at CollectAndShare (file:/data/data/com.lazyStudy/files/project/liulan.js:347:0)
    at articleStudy (file:/data/data/com.lazyStudy/files/project/liulan.js:253:0)
    at begin (file:/data/data/com.lazyStudy/files/project/liulan.js:405:0)
    at floating.js.js:94:0

**Comment by lgpersonal** [comment]
> Thread[ScriptThread-6[/data/user/0/com.lazyStudy/files/project/floating.js] (Spawn-0),5]: TypeError: Cannot call method "click" of null (file:/data/data/com.lazyStudy/files/project/liulan.js#347)
> TypeError: Cannot call method "click" of null
> at CollectAndShare (file:/data/data/com.lazyStudy/files/project/liulan.js:347:0)
> at articleStudy (file:/data/data/com.lazyStudy/files/project/liulan.js:253:0)
> at begin (file:/data/data/com.lazyStudy/files/project/liulan.js:405:0)
> at floating.js.js:94:0

刚看了，是旧版本的报错信息，估计为旧版本。你试试2.2.0
