### ISSUE TITLE
挑战答题中断

### ISSUE THREAD

**Issue by Rsweater** [lgpersonal/LazyStudy#66]
11:18:45.423/E: Thread[ScriptThread-2[/data/user/0/com.lazyStudy/files/project/floating.js] (Spawn-2),5]: TypeError: Cannot call method "child" of null (file:/data/data/com.lazyStudy/files/project/challengeAnswer.js#82)
TypeError: Cannot call method "child" of null
    at file:/data/data/com.lazyStudy/files/project/challengeAnswer.js:82:0
    at doChallengeAnswer (file:/data/data/com.lazyStudy/files/project/challengeAnswer.js:81:0)
    at main (file:/data/data/com.lazyStudy/files/project/challengeAnswer.js:130:0)
    at floating.js.js:115:0

**Comment by lgpersonal** [comment]
太正常不过了……autojs有时抓取不到控件

**Comment by Rsweater** [comment]
> 正常现象……autojs有时抓取不到控件

哦哦 明白了
