### ISSUE TITLE
到了文章分享和评论就跳乱码

### ISSUE THREAD

**Issue by hahahahan** [lgpersonal/LazyStudy#7]

**Comment by hahahahan** [comment]
Thread[ScriptThread-2[/data/user/0/com.lazyStudy/files/project/floating.js] (Spawn-0),5]: TypeError: Cannot call method "click" of null (file:/data/data/com.lazyStudy/files/project/liulan.js#347)
TypeError: Cannot call method "click" of null
    at CollectAndShare (file:/data/data/com.lazyStudy/files/project/liulan.js:347:0)
    at articleStudy (file:/data/data/com.lazyStudy/files/project/liulan.js:253:0)
    at begin (file:/data/data/com.lazyStudy/files/project/liulan.js:405:0)
    at floating.js.js:94:0

**Comment by lgpersonal** [comment]
随后更新

**Comment by hahahahan** [comment]
> 
> 
> 随后更新

2.1.0 每日答题可以了 但是文章分享收藏也是乱码

**Comment by lgpersonal** [comment]
试试2.2.0
